### ISSUE TITLE
uploaded image always is named `unknown`

### ISSUE THREAD

**Issue by prietus** [xray7224/p#33]
--title flag to mediagoblin set the title of the image but the file is named in mediagoblin to unknown, so the next upload allways fails because the unknown file already exists. 
i really do not know of the issue is mediagoblin related or not so i post here. If im wrong my apologies.

**Comment by xray7224** [comment]
It's not a p problem. This is a GNU MediaGoblin problem, this will be fixed in a later release of mediagoblin.

**Comment by prietus** [comment]
thanks for the clarification.
