### ISSUE TITLE
I uploaded an image but nothing shows up on my site

### ISSUE THREAD

**Issue by orblivion** [xray7224/p#40]
```p post image ../images/image.jpg --title "Test Upload"```

Seemed to go through. No std or err output. However I don't see the image on my site. I tried running: 

```p inbox```

And I got something like this:

```
yooser posted unknown.jpe
  yooser@media.example.com - 5 minutes ago
  Test Upload
  
  ![Image NonexNone][1]
  
     [1]: http://media.example.com/mgoblin_static/images/media_thumbs/image.png
```

(With only my username and my site URL changed)

However below that, it lists an entry from my site, which I uploaded manually long ago. So it seems that I'm on the right track but not quite there. Any idea what I need to do? Thanks.

**Comment by moggers87** [comment]
Sounds like a MediaGoblin issue to me.

**Comment by orblivion** [comment]
Ah. So, I'm on the 0.8 tag of Mediagoblin. Medigoblin's docs recommend `p` as one option for CLI.

**Comment by orblivion** [comment]
Should I open an issue on Mediagoblin instead? Or ask for more help on their IRC?

**Comment by moggers87** [comment]
Can you create a Pump.io account? http://pump.io/

If you can recreate this bug with a normal pump instance, then it's a p bug. If not, then tell the MediaGoblin people their software is broken :)

**Comment by orblivion** [comment]
Okay, seems to be Mediagoblin. I'll post it on their trac. Thanks!
