### ISSUE TITLE
README instructions cause an outdated version of PyPump to be installed

### ISSUE THREAD

**Issue by dachary** [xray7224/p#41]
When following instructions from the README

<pre>
$ p
Traceback (most recent call last):
  File "/home/loic/software/mediagoblin/p/virtualenv/bin/p", line 10, in <module>
    execfile(__file__)
  File "/home/loic/software/mediagoblin/p/p", line 28, in <module>
    from pypump.models.media import (Image, Video, Audio)
ImportError: No module named media
</pre>

It's a regression introduced by https://github.com/xray7224/p/commit/a3a2d687572b7c14f865ce491b7aa778e9ab4f0d introduces the regression

A workaround is to ```git reset --hard 2bd146e4f21bef1dc242a28a97b80aed8d6083bc```

**Comment by moggers87** [comment]
The issue is that the instructions in the README are not pulling in the latest version of PyPump from git.

A better workaround would be to fix the README instructions to point to `requirements.txt`

**Comment by moggers87** [comment]
@dachary if you run:

```
git pull && pip install -U -r requirements.txt
```

in your virtualenv, this should fix the issue for you.

**Comment by dachary** [comment]
cool, thanks !
