### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by phls** [xray7224/p#43]
Hi,

At first I packaged to use Python 3 only. But after the package was created, when I tried to authorize my account, I received this error:
NameError: name 'unicode' is not defined

I searched I little and found this:
http://stackoverflow.com/questions/36110598/nameerror-name-unicode-is-not-defined#comment59862846_36110598
"There is no such name in Python 3, no. You are trying to run Python 2 code in Python 3. In Python 3, unicode has been renamed to str."

If this is correct, I can't package to Python 3, right?

Thanks,

**Comment by craigmaloney** [comment]
I see the bug. Patching.

**Comment by craigmaloney** [comment]
https://github.com/xray7224/p/pull/44 should resolve it.

**Comment by emanuelstanciu** [comment]
Hi, I am seeing something similar when installing:

Command "/root/p/bin/python2 -c "import setuptools, tokenize;__file__='/root/p/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /root/p/

**Comment by emanuelstanciu** [comment]
please let me know if there's anything else I need to post

**Comment by moggers87** [comment]
Fixed by #44 (probably)
